var ab = 0;
var xv = '<h4><i class="fa fa-bars"></i><span></span><span>Navigation</span> Menu<span></span></h4>';
var xw = xv;
var xy = 0;
var cd = 0;
var ade;
var key = 0;
var value = "off";
var ratio;
var setter;
var updaton;
var success = 0;
var checker;
var setters;
var element;
var scrollOn, scroll;
var checkColor;
var updateObject;
var changeUpdate = 0;
var checkDataSync
var checkDataType;
var checkToScroll;
var captureExcoTitle;
var captureExcoName;
var holdDown = 0;
var set = 100;
var captureExcoLevel;
var captureEventHeader;
var normalSectionHeight;
var checkGalleryHeight;
var captureEventDescription;
var isUpdateDone;
var checkNavDisplay = 0;
var input_1, input_2, input_3, input_4;
var w = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
var v = window.innerHeight || document.documentElement.clientheight || document.body.clientheight;